name: Deploy Code to EC2 Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4

      - name: Copy repo files to /home/ubuntu
        run: |
          echo "Copying files from $GITHUB_WORKSPACE to /home/ubuntu ..."
          cp -r $GITHUB_WORKSPACE/* /home/ubuntu/
          cp -r $GITHUB_WORKSPACE/.[!.]* /home/ubuntu/ || true

