name: Deploy Code to EC2 Self-Hosted Runner

on:
  push:
    branches:
      - main   
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4

      - name: Sync repo files to /home/ubuntu
        run: |
          rsync -av --delete \
            --exclude='.git' \
            --exclude='logs/' \
            ./ /home/ubuntu/
